### ISSUE TITLE
Can't run flake8 with flake8-fixme plugin

### ISSUE THREAD

**Issue by nufrix** [tommilligan/flake8-fixme#6]
When I try to run `flake8` with `fixme` plugin installed, I get this error:
```
[nufrix@nufrix-thinkpad-t470p ~/Workspace/project] (project_venv) $ flake8 .
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/nufrix/Workspace/virtualenvs/emma_venv/lib/python3.6/site-packages/flake8/checker.py", line 682, in _run_checks
    return checker.run_checks()
  File "/home/nufrix/Workspace/virtualenvs/emma_venv/lib/python3.6/site-packages/flake8/checker.py", line 603, in run_checks
    self.process_tokens()
  File "/home/nufrix/Workspace/virtualenvs/emma_venv/lib/python3.6/site-packages/flake8/checker.py", line 581, in process_tokens
    self.check_physical_eol(token)
  File "/home/nufrix/Workspace/virtualenvs/emma_venv/lib/python3.6/site-packages/flake8/checker.py", line 643, in check_physical_eol
    self.run_physical_checks(token[4])
  File "/home/nufrix/Workspace/virtualenvs/emma_venv/lib/python3.6/site-packages/flake8/checker.py", line 558, in run_physical_checks
    column_offset, text = result
ValueError: not enough values to unpack (expected 2, got 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nufrix/Workspace/virtualenvs/emma_venv/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/nufrix/Workspace/virtualenvs/emma_venv/lib/python3.6/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/nufrix/Workspace/virtualenvs/emma_venv/lib/python3.6/site-packages/flake8/main/application.py", line 412, in run
    self._run(argv)
  File "/home/nufrix/Workspace/virtualenvs/emma_venv/lib/python3.6/site-packages/flake8/main/application.py", line 400, in _run
    self.run_checks()
  File "/home/nufrix/Workspace/virtualenvs/emma_venv/lib/python3.6/site-packages/flake8/main/application.py", line 318, in run_checks
    self.file_checker_manager.run()
  File "/home/nufrix/Workspace/virtualenvs/emma_venv/lib/python3.6/site-packages/flake8/checker.py", line 338, in run
    self.run_parallel()
  File "/home/nufrix/Workspace/virtualenvs/emma_venv/lib/python3.6/site-packages/flake8/checker.py", line 302, in run_parallel
    for ret in pool_map:
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 369, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 761, in next
    raise value
ValueError: not enough values to unpack (expected 2, got 0)
```
I have installed these versions for `flake8` libraries:
```
[nufrix@nufrix-thinkpad-t470p ~/Workspace/eproject] (project_venv) $ pip freeze | grep flake8
flake8==3.6.0
flake8-colors==0.1.6
flake8-docstrings==1.3.0
flake8-eradicate==0.2.0
flake8-polyfill==1.0.2
flake8-print==3.1.0
flake8-pytest==1.3
flake8-todo==0.7
flake8-fixme==1.1.0
```

**Comment by tommilligan** [comment]
Hey, thanks for trying the plugin out. As per the readme:

> The plugin officially supports Python >= 3.6 and flake8 >= 3.7.

If your project is compatible with `flake8 >= 3.7`, I recommend upgrading and retrying.

Unfortunately before `3.7`, flake8 did not support returning more than one error code from a line per check, ([see this PR](https://gitlab.com/pycqa/flake8/merge_requests/269)), so it's not a trivial compatibility to resolve.

**Comment by tommilligan** [comment]
If you do have a suggestion on how I could backport the functionality to `flake8 < 3.7`, I'd be up for implementing it

**Comment by tommilligan** [comment]
Closing as no response.
